# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NexysA7.xdc

# IP: ip/Q_input_data/Q_input_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Q_input_data || ORIG_REF_NAME==Q_input_data} -quiet] -quiet

# IP: ip/I_input_data/I_input_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==I_input_data || ORIG_REF_NAME==I_input_data} -quiet] -quiet
