# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/xfft_0/xfft_0.xci
# IP: The module: 'xfft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/xfft_0/xfft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/xfft_0/xfft_0.xci
# IP: The module: 'xfft_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/xfft_0/xfft_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
