# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/Q_input_data/Q_input_data.xci
# IP: The module: 'Q_input_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/Q_input_data/Q_input_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q_input_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/Q_input_data/Q_input_data.xci
# IP: The module: 'Q_input_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/Q_input_data/Q_input_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Q_input_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
