webtalk_init -webtalk_dir C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.sim/sim_1/behav/xsim/xsim.dir/FMCW_FFT_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 31 07:30:47 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "face15de-8092-46ba-82bd-c0d9392305c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "40ea869cb84f43c99ffda96ef2c064b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "258445100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.81_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16792_KB" -context "xsim\\usage"
webtalk_transmit -clientid 131476660 -regid "" -xml C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.sim/sim_1/behav/xsim/xsim.dir/FMCW_FFT_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.sim/sim_1/behav/xsim/xsim.dir/FMCW_FFT_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Dayalan/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.sim/sim_1/behav/xsim/xsim.dir/FMCW_FFT_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
