# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/naird/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/input_buffer_gen/input_buffer_gen.xci
# IP: The module: 'input_buffer_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/naird/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/input_buffer_gen/input_buffer_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_buffer_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/naird/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.srcs/sources_1/ip/input_buffer_gen/input_buffer_gen.xci
# IP: The module: 'input_buffer_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/naird/Desktop/FMCW_FFT_Radar/FMCW_FFT_Radar.gen/sources_1/ip/input_buffer_gen/input_buffer_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_buffer_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
